# version: '3.8'

version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./api/crud
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  app:
    build:
      context: ./interface/crud
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  postgres_data:

networks:
  net:
    driver: bridge


# services:
#   db:
#     image: postgres:alpine
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: crud
#     ports:
#       - "5432:5432"
#     networks:
#       - net

#   api:
#     build:
#       context: ./api/crud
#     ports:
#       - "8081:8081"
#     depends_on:
#       - db
#     networks:
#       - net

  # app:
  #   build:
  #     context: ./interface/crud
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - api

# networks:
#   net:
#     driver: bridge