spring:
  application:
    name: CRUD
  # Database connection settings
  datasource:
    url: jdbc:postgresql://localhost:5432/crud?serverTimezone=UTC
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  #JPA Settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
